pull_request_rules:
  - name: Automatic merge on tests passing
    conditions:
      - check-success=node-10
      - check-success=node-12
      - check-success=node-14
    actions:
      merge:
        method: merge
